### ISSUE TITLE
LibriTTS-360 pretrained checkpoints

### ISSUE THREAD

**Issue by arampacha** [SungFeng-Huang/Meta-TTS#3]
Hello, thanks for great work on MetaTTS paper and repo!

I've noticed there are "dev" configs for training on larger dataset including LibriTTS 360 and 500 subets. Do you have plans for releasing pretrained checkpoint and publishing results obtained with more data?

**Comment by SungFeng-Huang** [comment]
Hi, we didn't release those large-scale pretrained checkpoints simply because we are now refactoring our codes. We would probably release those checkpoints in the future after we finish our modifications and also update the checkpoint formats to make them compatible with the latest version.

Here's our speaker similarity results for the larger training dataset experiments, where "train-clean" indicates LibriTTS 100+360, and "train-all" indicates LibriTTS 100+360+500:
<img width="863" alt="截圖 2022-06-21 上午11 21 55" src="https://user-images.githubusercontent.com/22560619/174709558-e2882152-7da9-4006-a437-21a398d0fcb9.png">
As you can see, a larger training dataset might help MetaTTS with fine-tuning 5 steps (which is the number of inner-loop steps), but not helpful with more adaptation steps. On the other hand, pretraining with a larger dataset might help the baseline model with more adaptation steps, as the green line becomes comparable to the red line with 100 fine-tuning steps, while the improvement is not obvious.

**Comment by arampacha** [comment]
Thanks for such a detailed reply!
